import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "katex/dist/katex.min.css";
import "./globals.css";
import Nav from "@/components/Nav";
import AuthControls from "@/components/AuthControls";
import { AuthContextProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Curiosity Whiteboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <AuthContextProvider>
          <header className="border-b border-neutral-200 bg-white sticky top-0 z-50 h-14 shadow-sm">
            <nav className="mx-auto max-w-6xl px-3 h-full flex items-center gap-2">
              <Link
                href="/"
                aria-label="Curiosity Home"
                className="flex items-center"
              >
                <img
                  src="/textblack.png"
                  alt="Curiosity-edu"
                  className="h-11 w-auto"
                />
              </Link>
              <Nav />
              <div className="flex-1" />
              <AuthControls />
            </nav>
          </header>
          <main className="w-full bg-white overscroll-y-contain">
            {children}
          </main>
        </AuthContextProvider>
      </body>
    </html>
  );
}
